default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  variables:
    statement_timeout: 5000                  
    idle_in_transaction_session_timeout: 5000

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] || "postgres://inkline:postgres@localhost:5432/inkline_dev" %>

test:
  <<: *default
  url: <%= ENV["DATABASE_URL_TEST"] || "postgres://inkline:postgres@localhost:5432/inkline_test" %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %> 
